import { StyleSheet, Platform } from 'react-native';

export const adminStyles = StyleSheet.create({
  safeContainer: { flex: 1, backgroundColor: '#f8fafc' },
  container: { flex: 1 },
  centered: { flex: 1, justifyContent: 'center', alignItems: 'center', backgroundColor: '#f8fafc' },
  loadingText: { marginTop: 15, color: '#64748b', fontWeight: '500' },

  tabBarWrapper: {
    marginTop: 10,
    paddingHorizontal: 20,
    zIndex: 10,
  },
  tabBar: {
    backgroundColor: '#fff',
    padding: 8,
    borderRadius: 20,
    elevation: 8,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 10,
    flexDirection: 'row',
    alignItems: 'center',
  },
  tabItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 10,
    paddingHorizontal: 16,
    borderRadius: 14,
    marginRight: 8,
  },
  tabActive: { backgroundColor: '#0f172a' },
  tabText: { color: '#64748b', fontWeight: '600', fontSize: 13, marginLeft: 8 },
  tabTextActive: { color: '#fff' },

  tabContent: { padding: 20 },
  rowBetween: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  countBadge: { backgroundColor: '#f1f5f9', paddingHorizontal: 12, paddingVertical: 6, borderRadius: 12 },
  countText: { fontSize: 12, fontWeight: 'bold', color: '#64748b' },
  statsGrid: { flexDirection: 'row', flexWrap: 'wrap', justifyContent: 'space-between' },
  statCard: {
    width: '48%',
    padding: 20,
    borderRadius: 24,
    marginBottom: 15,
    borderWidth: 1,
    borderColor: 'rgba(0,0,0,0.02)',
  },
  iconBox: {
    width: 44,
    height: 44,
    borderRadius: 14,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 12,
  },
  statVal: { fontSize: 24, fontWeight: 'bold', color: '#0f172a' },
  statLab: { fontSize: 12, color: '#64748b', marginTop: 2, fontWeight: '500' },

  summarySection: { marginTop: 10 },
  sectionTitle: { fontSize: 20, fontWeight: 'bold', color: '#0f172a', marginBottom: 15 },
  infoCard: {
    backgroundColor: '#fff',
    padding: 20,
    borderRadius: 24,
    elevation: 2,
    shadowColor: '#000',
    shadowOpacity: 0.05,
    shadowRadius: 10,
  },
  infoRow: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 20 },
  infoItem: { flex: 1 },
  infoLabel: { fontSize: 12, color: '#64748b', marginBottom: 4, textTransform: 'uppercase', letterSpacing: 0.5 },
  infoVal: { fontSize: 16, fontWeight: 'bold', color: '#0f172a' },

  requestCard: { backgroundColor: '#fff', padding: 20, borderRadius: 24, marginBottom: 15, elevation: 2 },
  cardHeader: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 15 },
  reqTypeBadge: { paddingHorizontal: 10, paddingVertical: 5, borderRadius: 10 },
  statusBadge: { paddingHorizontal: 10, paddingVertical: 5, borderRadius: 10 },
  badgeText: { fontSize: 10, fontWeight: '800', color: '#64748b' },
  statusLabel: { fontSize: 10, fontWeight: '800' },
  reqTitle: { fontSize: 18, fontWeight: 'bold', color: '#0f172a', marginBottom: 10 },
  reqMeta: { flexDirection: 'row', alignItems: 'center', flexWrap: 'wrap' },
  reqDetail: { fontSize: 13, color: '#64748b', marginLeft: 4 },
  dot: { width: 4, height: 4, borderRadius: 2, backgroundColor: '#cbd5e1', marginHorizontal: 8 },

  actionRow: { flexDirection: 'row', marginTop: 20, gap: 10 },
  approveBtn: { flex: 1, backgroundColor: '#0f172a', paddingVertical: 14, borderRadius: 14, flexDirection: 'row', justifyContent: 'center', alignItems: 'center', gap: 6 },
  rejectBtn: { flex: 1, backgroundColor: '#ef4444', paddingVertical: 14, borderRadius: 14, flexDirection: 'row', justifyContent: 'center', alignItems: 'center', gap: 6 },
  btnText: { color: '#fff', fontWeight: 'bold', fontSize: 14 },

  userCard: { backgroundColor: '#fff', padding: 20, borderRadius: 24, marginBottom: 15, elevation: 2 },
  userHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start' },
  userMain: { flexDirection: 'row', alignItems: 'center' },
  userAvatar: { width: 50, height: 50, borderRadius: 16, marginRight: 12 },
  userName: { fontSize: 16, fontWeight: 'bold', color: '#0f172a' },
  roleBadge: { alignSelf: 'flex-start', paddingHorizontal: 8, paddingVertical: 2, borderRadius: 6, marginTop: 4 },
  roleText: { fontSize: 10, fontWeight: 'bold' },
  userActionBtn: { backgroundColor: '#f1f5f9', paddingHorizontal: 14, paddingVertical: 8, borderRadius: 12 },
  userActionText: { fontSize: 12, fontWeight: '700', color: '#0f172a' },
  userDetails: { marginTop: 15, paddingTop: 15, borderTopWidth: 1, borderTopColor: '#f1f5f9' },
  detailRow: { flexDirection: 'row', alignItems: 'center', marginBottom: 6 },
  detailText: { fontSize: 13, color: '#64748b', marginLeft: 8 },

  courseCard: { backgroundColor: '#fff', padding: 20, borderRadius: 24, marginBottom: 15 },
  courseBadge: { backgroundColor: '#eff6ff', paddingHorizontal: 10, paddingVertical: 4, borderRadius: 8 },
  courseBadgeText: { fontSize: 11, fontWeight: 'bold', color: '#2563eb' },
  pendingLabel: { fontSize: 10, fontWeight: 'bold', color: '#d97706' },
  courseTitle: { fontSize: 18, fontWeight: 'bold', color: '#0f172a', marginTop: 12 },
  courseDesc: { fontSize: 14, color: '#64748b', marginTop: 6, lineHeight: 20 },
  courseMeta: { flexDirection: 'row', justifyContent: 'space-between', marginTop: 15 },
  instructorText: { fontSize: 12, color: '#94a3b8' },
  linkText: { fontSize: 12, color: '#2563eb', fontWeight: '600' },

  donationCard: { backgroundColor: '#fff', padding: 20, borderRadius: 24, marginBottom: 12 },
  donationHeader: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 15 },
  donationAmt: { fontSize: 18, fontWeight: 'bold', color: '#0f172a' },
  donationDate: { fontSize: 12, color: '#94a3b8' },
  donationUsers: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', backgroundColor: '#f8fafc', padding: 12, borderRadius: 16 },
  userBox: { flex: 1 },
  userLabel: { fontSize: 9, fontWeight: '800', color: '#94a3b8', marginBottom: 2 },
  userNameSmall: { fontSize: 13, fontWeight: 'bold', color: '#1e293b' },

  emptyContainer: { alignItems: 'center', paddingVertical: 40 },
  emptyText: { color: '#94a3b8', marginTop: 12, fontSize: 14 },

  addTaskBtn: { backgroundColor: '#0f172a', width: 44, height: 44, borderRadius: 15, justifyContent: 'center', alignItems: 'center' },
  subText: { color: '#64748b', marginBottom: 20, fontSize: 14 },

  modalOverlay: { flex: 1, backgroundColor: 'rgba(15, 23, 42, 0.4)', justifyContent: 'center', padding: 20 },
  modalContent: { backgroundColor: '#fff', borderRadius: 30, padding: 25, elevation: 10 },
  modalHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 25 },
  modalTitle: { fontSize: 22, fontWeight: 'bold', color: '#0f172a' },
  input: { backgroundColor: '#f8fafc', padding: 16, borderRadius: 16, marginBottom: 15, borderWidth: 1, borderColor: '#f1f5f9' },
  label: { fontSize: 14, fontWeight: 'bold', color: '#0f172a', marginBottom: 12 },
  volSelect: { marginBottom: 25 },
  volChip: { paddingHorizontal: 16, paddingVertical: 10, borderRadius: 14, backgroundColor: '#f1f5f9', marginRight: 10 },
  volChipActive: { backgroundColor: '#0f172a' },
  volChipText: { color: '#64748b', fontWeight: '600' },
  volChipTextActive: { color: '#fff' },
  submitBtn: { backgroundColor: '#0f172a', padding: 18, borderRadius: 18, alignItems: 'center' },
  btnTextLarge: { color: '#fff', fontSize: 16, fontWeight: 'bold' },
  btnDisabled: { opacity: 0.6 },
  adminDocActionBtn: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    backgroundColor: '#f0f9ff',
    padding: 12,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#bae6fd',
    marginTop: 8,
  },
  adminDocActionText: {
    fontSize: 13,
    color: '#0077cc',
    fontWeight: '700',
  },
});
